version: '3.8'

services:
  db:
    ports:
      - ${POSTGRES_PORT}:5432
  django:
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    depends_on:
      - db
  node:
    ports:
      - ${NODE_PORT}:${NODE_PORT}
