version: '3.8'

services:
  django:
    build:
      context: ./bin/django/
      dockerfile: Dockerfile.prod
    depends_on:
      - db
  nginx:
    container_name: hr-ngnix
    build: ./bin/nginx/
    volumes:
      - ./frontend/dist/:/opt/app/frontend/dist/
      - ./backend/static/:/opt/app/backend/static/
      - ./backend/media/:/opt/app/backend/media/
    ports:
      - 80:80
    depends_on:
      - django
    restart: always