# Generated by Django 4.0.6 on 2023-04-04 17:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('slug', models.SlugField(default='', unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('fully_description', models.TextField(default='')),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('experience', models.IntegerField()),
                ('employment', models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('PR', 'Project')], default='FT', max_length=2)),
                ('image', models.ImageField(blank=True, default='projects/images/default.png', null=True, upload_to='projects/images')),
                ('total_votes', models.IntegerField(default=0)),
                ('votes_average', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('demo_link', models.CharField(blank=True, max_length=500, null=True)),
                ('source_link', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
