# Generated by Django 4.0.6 on 2023-04-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
