# Generated by Django 4.0.6 on 2023-03-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_review_review_text_alter_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='employment',
            field=models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('PR', 'Project')], default='FT', max_length=2),
        ),
        migrations.AddField(
            model_name='project',
            name='experience',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
