# Generated by Django 4.0.6 on 2023-03-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='votes_ratio',
        ),
        migrations.AddField(
            model_name='project',
            name='fully_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='votes_average',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
