# Generated by Django 4.0.6 on 2023-03-14 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_project_votes_average'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
    ]
