# Generated by Django 4.0.6 on 2023-04-24 03:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilereview',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='projectreview',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='profilereview',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectreview',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
