# Generated by Django 4.0.6 on 2023-04-01 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_profile_projects_profile_projects_count'),
        ('reviews', '0003_projectreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileReview',
            fields=[
                ('review_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reviews.review')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            bases=('reviews.review',),
        ),
    ]
