# Generated by Django 4.0.6 on 2023-04-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
