# Generated by Django 4.0.6 on 2023-04-09 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_remove_employerprofile_name_and_more'),
        ('responses', '0002_response_is_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='response',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employerprofile'),
        ),
    ]
