# Generated by Django 4.0.6 on 2023-04-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
