# Generated by Django 4.0.6 on 2023-04-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employeeprofile_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='title',
            field=models.CharField(default='ozon tech', max_length=255),
            preserve_default=False,
        ),
    ]
