# Generated by Django 4.0.6 on 2023-02-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_intro_profile_second_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.SlugField(default='none', unique=True),
        ),
    ]
