# Generated by Django 4.0.6 on 2023-04-04 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_response_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='title',
        ),
    ]
