# Generated by Django 4.0.6 on 2023-04-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_response_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='responses',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='responses',
            field=models.ManyToManyField(blank=True, to='users.response'),
        ),
    ]
