# Generated by Django 4.0.6 on 2023-04-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_employerprofile_responses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='work_places',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='work_places',
            field=models.ManyToManyField(blank=True, to='users.workplace'),
        ),
    ]
