# Generated by Django 4.0.6 on 2023-04-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_employeeprofile_work_places_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='experience',
            field=models.SmallIntegerField(default=0),
        ),
    ]
