# Generated by Django 4.0.6 on 2023-04-04 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_employeeprofile_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='responses',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
