# Generated by Django 4.0.6 on 2023-04-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_employerprofile_responses_delete_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='second_name',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_name',
            field=models.CharField(default='yandex', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
