# Generated by Django 4.0.6 on 2023-04-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_employeeprofile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
