# Generated by Django 4.0.6 on 2023-02-28 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_skill_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='slug',
        ),
    ]
