# Generated by Django 4.0.6 on 2023-03-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_profile_projects_profile_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='projects',
        ),
        migrations.AddField(
            model_name='profile',
            name='projects_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
