# Generated by Django 4.0.6 on 2023-04-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_profilereview'),
        ('users', '0020_remove_profile_projects_profile_projects_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='+', to='reviews.profilereview'),
        ),
    ]
