name: CI
on:
  pull_request:
    branches: [master]
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - name: Get repository code
      uses: actions/checkout@v3
    - name: Init app
      run: ./project.sh init
  frontend:
    runs-on: ubuntu-latest
    needs: [init]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create .env file
      run: ./project.sh cp .env.prod .env
    - name: Docker compose up
      run: docker compose --profile dev up -d
    - name: Generate endpoints
      run: ./project.sh generateAPI
    - name: Lint
      run: ./project.sh lint_frontend
    - name: Build
      run: ./project.sh build_frontend
  backend:
    runs-on: ubuntu-latest
    needs: [init]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create .env file
      run: ./project.sh cp .env.prod .env
    - name: Docker compose up
      run: docker compose up -d
    - name: Collect static
      run: ./project.sh collectstatic
    - name: Make migrations and migrate
      run: ./project.sh migrate