name: CI
on:
  pull_request:
    branches: [master]
jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create .env file
      run: cd ../ && cp .env.test .env && cd ./frontend
    - name: Install yarn
      run: npm i -G yarn
    - name: Install dependencies
      run: yarn install
    - name: Generate endpoints
      run: yarn generateAPI
    - name: Test
      run: yarn test
    - name: Lint
      run: yarn lint
    - name: Build
      run: yarn vite build
  backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create .env file
      run: cp .env.test .env
    - name: Build containers
      run: ./project.sh init_back_ci
    - name: Docker compose up
      run: docker compose up -d
    - name: Collect static
      run: ./project.sh collectstatic
    - name: Make migrations and migrate
      run: ./project.sh migrate