name: CI
on:
  pull_request:
    branches:
      - master
jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Get repository code
      uses: actions/checkout@v3
    - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/yarn-lock.json') }}
    - name: Yarn setup
      uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
    - name: Install dependencies
      run: yarn install
    - name: Build
      run: yarn build
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python v3.8
        uses: actions/setup-python@v4
        with:
           python-version: 3.8
      - name: Install requirements
        run: pip install -r **/requirements.txt